### ISSUE TITLE
Support for encryption on widevine codec

### ISSUE THREAD

**Issue by snugglej** [thorhop/com.vivaldi.Vivaldi#3]
I don't think libsecret is working properly because when I test widevine codec compatibility it looks like the keystore is missing. 

I believe in my previous repo that I was building for Vivaldi I had to include `"--talk-name=org.freedesktop.secrets"` to get this working.

How to test widevine support and see that encyrption isn't supported: https://bitmovin.com/demos/drm

**Comment by thorhop** [comment]
Just like the `com.microsoft.edge` package, we bundle our own little secrets from GNOME archive which is built during the flatpaking and we do give the app access to `--talk-name=org.freedesktop.secrets`. The real issue is availability and distribution of the widevine library. Vivaldi doesn't even bundle widevine, because they haven't gotten permission to do so. Their solution is to rely on chromes distribution, so much so that the `WidevineCdm` file is a symlink to `/opt/google/chrome/WidevienCdm`.

Therefore, it's a completely seperate issue - and that is how to get `WidevineCdm` in to a Vivaldi install without distributing it - i.e similarly to how Vivaldi already installs `libffmpeg.so` via `ffmpeg-update`.
